# Generated by Django 2.2.6 on 2019-10-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdrive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
