# Generated by Django 2.2.5 on 2019-10-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrive', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('files', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
